title: FROGHamil
author: Sylvain PITIÉ
email: sylvain.pitie@u-paris.fr
description: a script to get the Overlap and Fock matrix from a Gaussian16 calculation
twitter_username: PitiéSylvain

theme: jekyll-theme-slate

