title: ircbyhand
author: Sylvain PITIÉ
email: sylvain.pitie@u-paris.fr
description: Fortran script for IRC using Freq calculation provide by Gaussian16.
twitter_username: PitiéSylvain

theme: jekyll-theme-slate

